### ISSUE TITLE
Bad practice

### ISSUE THREAD

**Issue by purpleidea** [holocm/holo#11]
This is a really bad idea:

In Makefile:

>   --release="Holo $(shell grep 'var version =' src/holo/main.go | cut -d'"' -f2)" \

Instead, generate your version somehow (see my Makefile for one possibility), and put it into the go binary during compile. Here is an example:

https://github.com/purpleidea/mgmt/blob/master/Makefile#L28

The golang code now just looks like:

```
// set at compile time
var (
    version string
)
```

HTH,
James

**Comment by purpleidea** [comment]
You're welcome! :)

**Comment by majewsky** [comment]
I actually encountered a problem with this change. Since I rely on `git describe` all the time, stuff breaks when I'm building from a release tarball.

**Comment by atweiden** [comment]
https://autorevision.github.io/ maybe this helps

**Comment by purpleidea** [comment]
@majewsky Just look at how I do it in my Makefile, and you should have the solution you need. Cheers
https://github.com/purpleidea/mgmt/blob/master/Makefile

**Comment by majewsky** [comment]
AFAICS both approaches miss the point because the problems emerge when I'm not building from a git clone, but from a release tarball (where you don't have the `.git` directory). [This commit](https://github.com/holocm/holo-build/commit/8e4627d02d2aa226556bccd20a2e6784ecad85f1) is how I fixed it in holo-build, and I'll adapt that to other relevant repos, like this one.

**Comment by purpleidea** [comment]
@majewsky nice :)
