### ISSUE TITLE
`sort` does not work on busybox systems

### ISSUE THREAD

**Issue by ghost** [holocm/holo#37]
This causes the unit tests to fail. Instead of using a symlink, one could use an script like

```
#!/usr/bin/sort
```

which will deliver the right argv[0] value to busybox.

**Comment by LukeShu** [comment]
Am I understanding correctly that the issue is the test holoscripts implemented as:
```
symlink   0777 ./usr/share/holo/files/02-holoscripts/etc/plain-through-link.conf.holoscript
/usr/bin/sort
```
?

If so, here's a better write-up:

----

One of the things the tests check for is that holoscripts can be implemented as symlinks to other programs.  They do this by having several holoscripts that  are implemented as links to `/usr/bin/sort` or `/usr/bin/uniq`.  On busybox systems, those are implemented as links to the busybox monobinary, which decides which program to run based on `argv[0]`.  Since that will be `.../whatever.holoscript` instead of `.../sort` or `.../uniq`, it won't correctly figure out which program to run, and the tests will fail.

**Comment by majewsky** [comment]
What I would propose is to add a new set of wrapper scripts like:

**Comment by majewsky** [comment]
What I would propose is to add a new set of wrapper scripts like:

```
$ cat test/binaries/sort
#!/bin/sh
exec sort "$@"
$ chmod +x test/binaries/sort
```

And then change the symlink holoscripts to point to these instead. That way, we can have our cake (as in: testing holoscripts that are symlinks) and eat it too (as in: completing the tests on Busybox-based distros). @nero Would you fancy making a PR for that?

**Comment by ghost** [comment]
Tests dont work on alpine because `go tools cover` is missing. Go version is `go1.9.4`. Still investigating.

**Comment by majewsky** [comment]
I implemented the approach that I suggested in https://github.com/holocm/holo/issues/37#issuecomment-365200850 in 22108f17d2. @nero Please check, and re-open if this is not fixing the problem for you.

**Comment by ghost** [comment]
This issue does not appear again. There is still another issue with the packaging of the go runtime on alpine.
