### ISSUE TITLE
Error "skipping target ... not a manageable file"

### ISSUE THREAD

**Issue by mipimipi** [holocm/holo#48]
During an installation of Arch Linux, I would like holo-files to add a file to /etc/sudoers.d. In my PKGBUILD I have this line:

    install -Dm666 mipi-base.sudoers "${pkgdir}/usr/share/holo/files/10-sudoers/etc/sudoers.d/mipi-base"

When I execute holo apply I get the above mentioned error message. I searched for a reason but didn't find any. Could you help me? Thanks.

**Comment by LukeShu** [comment]
There are 3 cases that Holo currently supports:

|What you want|Where to have the PKGBUILD put the file|
|----|----|
| You want to provide a file that no other package provides | `${pkgdir}/FILENAME`
| You want to edit a file that another package provides | `${pkgdir}/usr/share/holo/files/NN-FOO/FILENAME.holoscript`
| You want to completely override a file another package provides| `${pkgdir}/usr/share/holo/files/NN-FOO/FILENAME`

Since I assume that no other package provides `/etc/sudoers.d/mipi-base`, you don't need to mess with `/usr/share/holo/files/`.  Put another way, providing files that are only owned by one package is something that pacman already does a good job of handling; where holo-files comes in is enabling *multiple* packages to have a say on a *single* file, which is something that pacman can't handle.

(Note that if you do use `/usr/share/holo/files/`, then you should `depends=()` on the package that includes the file you're editing/overriding)

**Comment by mipimipi** [comment]
I didn't know that holo does not support that use case, but you are right: That's not necessary since it can be used differently. Thanks!
