### ISSUE TITLE
Current directory of "holoscript"s

### ISSUE THREAD

**Issue by mipimipi** [holocm/holo#50]
In a .holoscript ressource file, I want to inject the content of a file (let's call it "file-A") into the target file via the read action of sed. The problem is that I do not know how to access file-A in the .holoscript file. I can put file-A wherever I want, and I tried out different options ( a: storing it in the same directory like the target file, b: storing it in the same directory like the .holoscript file). None of these options work. Where (i.e. in which directory) is the .holoscript file executed? If I knew this, I could put file-A there and simply access it via `sed -e '.../r file-A'` fro the .holoscript file. Thanks

**Comment by majewsky** [comment]
According to https://github.com/holocm/holo/blob/1bed970ea3dc084de51fe0b5b5b1acbcdbf4b6eb/cmd/holo-run-scripts#L49, the script is run in the root directory `/`, matching the behavior of e.g. Pacman's install scripts and hooks. This behavior is undocumented in the manpage. If you don't want to rely on undocumented behavior, you can always use absolute paths.
Am 11.10.19, 15:23, Michael Picht <notifications@github.com> schrieb:
In a .holoscript ressource file, I want to inject the content of a file (let's call it "file-A") into the target file via the read action of sed. The problem is that I do not know how to access file-A in the .holoscript file. I can put file-A wherever I want, and I tried out different options ( a: storing it in the same directory like the target file, b: storing it in the same directory like the .holoscript file). None of these options work. Where (i.e. in which directory) is the .holoscript file executed? If I knew this, I could put file-A there and simply access it via sed -e '.../r file-A' fro the .holoscript file. Thanks

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/holocm/holo/issues/50?email_source=notifications\u0026email_token=AAAGA6G4OO53LK32WLPTVDTQOB46ZA5CNFSM4I7ZYIAKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HRGVR7Q",
"url": "https://github.com/holocm/holo/issues/50?email_source=notifications\u0026email_token=AAAGA6G4OO53LK32WLPTVDTQOB46ZA5CNFSM4I7ZYIAKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HRGVR7Q",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by majewsky** [comment]
According to: https://github.com/holocm/holo/blob/1bed970ea3dc084de51fe0b5b5b1acbcdbf4b6eb/cmd/holo-run-scripts#L49
The script is run in the root directory `/`, matching the behavior of e.g. Pacman's install scripts and hooks. This behavior is undocumented in the manpage. If you don't want to rely on undocumented behavior, you can always use absolute paths.

**Comment by mipimipi** [comment]
Thanks for the quick reply.
